my_int_value = int (input ("введите целое число: "))
print ("Вы ввели ", my_int_value)
my_float_value = float (my_int_value)
my_str_value = str (my_int_value)
print ("преобразование к типу float: ", my_float_value)
print ("преобразование к типу str: ", my_str_value)
